### ISSUE TITLE
QoS Receive Example

### ISSUE THREAD

**Issue by pascaldekloe** [soypat/natiu-mqtt#1]
How would a QoS 2 [exactly once] receive look like? An example in the README and/or a godoc example would be handy.

**Comment by soypat** [comment]
This library does not yet support QoS 2 as per the MQTT standard... Though if you use TCP as a underlying transport then you are guaranteed the receipt of the message exactly once if no error is returned.

As the library stands now is not in it's final state- there are some changes to the Client implementation I have on the drawing board. I also wish to make it easier to use/more intuitive.

**Comment by pascaldekloe** [comment]
The readme now states it supports the standard. Would be good to mention QoS absense.

**Comment by soypat** [comment]
You are absolutely right. I have added it to the readme. Thank you!

**Comment by pascaldekloe** [comment]
Maybe the following example will help you with the picture. https://github.com/pascaldekloe/mqtt/blob/master/client.go#L1026

**Comment by pascaldekloe** [comment]
https://github.com/pascaldekloe/mqtt/blob/3362e6ca7cc95fd2f77db030bf4e531f36b9f708/request.go#L592

**Comment by pascaldekloe** [comment]
Sure, TCP ensures reception. 😄 The message may be lost thereafter though due to errors, crashes, buffer capacity and what not. MQTT goes one step further by requiring persistence before acknowledgement.

QoS 2 is not that commonly used. QoS 1 [at least once] is the big one. It may not be that complicated if you limit yourself to one in-flight message only.

I do sympathise with the single threaded concept. It is hard to visualize how that works in practice though. You have to read regularly or risk drops and/or timeouts with the broker. And once you read you're blocked for data. One could do short read timeouts yet those are expensive—defeating the purpose. Things get worse on slow/unstable connections, which is exactly an area where the protocol shines otherwise.

Nothing wrong with limiting the scope to QoS 0 of course. Picking a few dedicated use-cases and do those well. Either way, enjoy the journey. 🍸
